services:
  ecobin-sensor-data-service:
    container_name: ecobin_sensor_data_service
    build:
      context: ./EcoBin-Sensor-Data-Service
      dockerfile: Dockerfile
    ports:
      - "6028:6028"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://0.0.0.0:6028"
      ConnectionStrings__DefaultConnection: "Host=ecobin-sensor-data-db;Port=5432;Database=ecobin_sensor_data_db_production;Username=myuser;Password=mypassword"
    depends_on:
      - ecobin-sensor-data-db
    restart: always
    networks:
      - ecobin-network

  ecobin-sensor-data-db:
    container_name: ecobin_sensor_data_db
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ecobin_sensor_data_db_production
    ports:
      - "5433:5432"
    volumes:
      - ecobin_sensor_data:/var/lib/postgresql/data
    restart: always
    networks:
      - ecobin-network

  ecobin-user-data-service:
    container_name: ecobin_user_data_service
    build:
      context: ./EcoBin-User-Data-Service
      dockerfile: Dockerfile
    ports:
      - "6274:6274"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://0.0.0.0:6274"
      EcoBinSensorDataApi__BaseUrl: "http://ecobin-sensor-data-service:6028"
    restart: always
    networks:
      - ecobin-network

volumes:
  ecobin_sensor_data:

networks:
  ecobin-network:
